name: Build with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Change to windows-latest or macos-latest if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use PyInstaller Action
        uses: JackMcKew/pyinstaller-action@v2
        with:
          path: main.py  # Replace with your script's entry point
          spec: ""  # If you have a .spec file, provide its path here
          options: "--onefile --name my_app"  # Adjust options as needed

      - name: Upload Built Executable
        uses: actions/upload-artifact@v4
        with:
          name: built-executable
          path: dist/my_app*  # Uploads the compiled binary
