name: Package Application with Pyinstaller

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: build

    - uses: actions/upload-artifact@v4
      with:
        name: my-app
        path: dist/windows
