name: Build Workflow

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8.10'
          architecture: 'x86'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller build.spec
      - name: Move Config File to Dist Folder
        run: move app.config dist\app.config
        shell: cmd
      - name: Move HALUtilities to Dist Folder
        run: move HalUtilities.exe dist\HalUtilities.exe
        shell: cmd
      - uses: actions/upload-artifact@v4
        with:
          name: Redbox Duplicator Remover
          path: D:\a\RedboxDuplicateRemover\RedboxDuplicateRemover\dist\
