
name: Build with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allows manual triggering

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.8.7-32'
          spec: 'workflows/Duplicate Remover.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'My executable'
          options: --onefile, --name "Duplicate RemoverTest", --icon="images/redboxTinkering.ico"
